--Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from customer
where discount_applied= 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select category,round(AVG(review_rating::numeric),2)from customer
group by category

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
round(AVG(purchase_amount::numeric),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
round(AVG(purchase_amount::numeric),2)
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100*sum(case when discount_applied= 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
--Q8. What are the top 3 most purchased products within each category?
select item_purchased,count(customer_id)
from customer 
group by item_purchased
or
limit 3
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) as revenue
from customer
group by age_group


